### ISSUE TITLE
Request: Project Introduction

### ISSUE THREAD

**Issue by vatterspun** [alexporrello/TWBoilerplateMacros#2]
Recommend writing something up along the lines of "This project is ___." by way of introduction.

A possible explanation:

"This project is a series of automated tools for document management written in Visual Basic for Microsoft Word.  The macros provided have been tested successfully on multiple Windows machines running Word 2016.

If you're feeling expressive:

* Something about welcoming comments and participation
* Something about possible future development / next steps
* About the author (if you want this to be a resume builder)

**Comment by alexporrello** [comment]
Excellent feedback. I hacked together the docs for our document control specialists who will be using the tools, but a short introduction certainly couldn't hurt.

**Comment by vatterspun** [comment]
Cool, glad that was useful
